
title: 'PATI: A Projection-Based Augmented Table-Top Interface for Robot Programming'
description: Yuxiang Gao &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Chien-Ming Huang
show_downloads: true
theme: jekyll-theme-cayman